### ISSUE TITLE
Build issue on Android with distributionUrl set to gradle-4.4-all.zip

### ISSUE THREAD

**Issue by gerryhigh** [builttoroam/flutter_plugins#104]
I'm on master and updated Flutter to the latest release today and name am getting this error in building:

] * What went wrong:
[        ] [        ] A problem occurred evaluating root project 'device_calendar'.
[        ] [        ] > Failed to apply plugin [id 'com.android.library']
[        ] [        ]    > Minimum supported Gradle version is 4.10.1. Current version is 4.4. If using the gradle
wrapper, try editing the distributionUrl in .... gradle\wrapper\gradlewrapper.properties to 4.10.1-all.zip

As a work around I've cloned the project and edited the above mentioned file to fix the issue.

**Comment by MaikuB** [comment]
Thanks raising this. Updated it as part of PR #102 that will be released soon

**Comment by MaikuB** [comment]
Published a new version so this issue should be resolved. Note though that we build against the stable channel of Flutter
