### ISSUE TITLE
Calendar event reminder

### ISSUE THREAD

**Issue by lgArlequin** [builttoroam/flutter_plugins#105]
Hi, nice plugin!, is there any way to set a reminder when creating the event?
Thanks!

**Comment by nickrandolph** [comment]
@lgArlequin not currently - would love your input if you want to submit a PR....

**Comment by finpro-svn** [comment]
I also think that the plugin should be improved so that it is possible to add reminder with the event.

**Comment by nickrandolph** [comment]
We've added this to the backlog for next version (see project boards) Happy to accept PRs from anyone who wants this feature built before then

**Comment by MaikuB** [comment]
The ability to set multiple reminders based on time relative to the start of the event has been added. Will close this now

**Comment by TinchoOlivari** [comment]
This worked for me: https://github.com/builttoroam/device_calendar/issues/210#issuecomment-606325699

> "Ah good point, no idea why reminder is not part of the constructor, I'll make sure to add it in the next release. As a workaround, you can directly assign to the property. For example:"


> ```dart
> var reminders = List<Reminder>();
> reminders.add(Reminder(minutes: 30));
> 
> var event = Event("1", title: "Test Event");
> event.reminders = reminders;
> ```
