### ISSUE TITLE
"New events must specify a calendar id"

### ISSUE THREAD

**Issue by kraxarn** [builttoroam/flutter_plugins#113]
Trying to add events to a calendar (with calendar id specified) but it doesn't work.
Code:
```dart
final devCal = DeviceCalendarPlugin();
final cals = (await devCal.retrieveCalendars()).data;
final cal = Calendar(
    id: "calid",
    name: "Calendar Name",
    isReadOnly: false
);
cals.add(cal);

final event = Event("calid".
    eventId: "evid",
    // ...
);
final result = await devCal.createOrUpdateEvent(event);
final errors = result.errorMessages;
/* errors:
 * [599] Device calendar plugin ran into an issue. Platform specific exception 
 * [500], with message :"New events must specify a calendar id", has been thrown.
 */
```

**Comment by MaikuB** [comment]
looks like you're trying to add a new calendar which isn't supported. events can only be added to an existing calendar

**Comment by kraxarn** [comment]
Then I guess this is both a feature request for it to be added and a bug report because it lets me add a calendar and for the incorrect error message (should probably say something like "calendar not found").

**Comment by MaikuB** [comment]
Being able to add to the list of calendars returned will be addressed in #112. However, with regards to adding calendars, from what I've seen I don't think this is possible. Particularly with creating calendars that are synchronised with servers on Android. If you find a way to do so then we'd be happy to take a PR

**Comment by MaikuB** [comment]
Bug has been fixed now. Will close this and add an issue on the board around being able to add calendars. PRs are welcome

**Comment by kraxarn** [comment]
After checking the Android documentation, I found that in order to actually create a calendar, you have to do it from a sync adapter, which involves having to set up a device account, background service etc. The same goes for adding locations to an event I believe. I don't know about iOS.
