### ISSUE TITLE
Returning NULL on released version

### ISSUE THREAD

**Issue by rsk-pr** [builttoroam/flutter_plugins#114]
I implemented the device_callendar 0.2.2 and everything works great on debug but when I release the app on android, the device asks for the permission to access the calendar just fine but the list of calendars come back null. The amount of calendars retrieved from the release version come back the same as in debug but the .id and the .name come back null for each calendar. On iOS released version everything works great as in debug. Am I missing something?

I trippled checked my android manifest and the permisions are there:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.app.myapp">

    <uses-permission android:name="android.permission.READ_CALENDAR"/>
    <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
    <uses-permission android:name="android.permission.INTERNET"/>

**Comment by rsk-pr** [comment]
I seems the problem is proguard. Once I enable it, the device_calendar returns null.

**Comment by rsk-pr** [comment]
-keep class com.builttoroam.devicecalendar.** { *; }

**Comment by nickrandolph** [comment]
@MaikuB did we add info somewhere on the use of proguard - can we elevate it to the Readme so it's easy for developers to find
I'm reopening this item just so we can track the update to the docs

**Comment by MaikuB** [comment]
Yes another issue was raised on this and the change is currently in #112

**Comment by nickrandolph** [comment]
Closing this item as it's addressed in linked PR
