### ISSUE TITLE
Any documentation please

### ISSUE THREAD

**Issue by santiagoalmeidabolannos** [builttoroam/flutter_plugins#119]
Please can you add some examples? I am interested on add reminders in the calendar. Thanks

**Comment by SaurabhSM** [comment]
Please add some documentation

**Comment by MaikuB** [comment]
There's an example app in the repo https://github.com/builttoroam/flutter_plugins/tree/master/device_calendar/example. FYI, it's pretty standard that plugins have an example app at a location like that relative to the plugin as it's comes out of the box with the template for creating a plugin

**Comment by SaurabhSM** [comment]
Yes there is an example app and yes there is standard procedure to add a example. But when i'm writing code for project i would rather look up API reference rather than hunting into example code what functionality of code is.

**Comment by MaikuB** [comment]
To clarify, my reply was in relation to the original poster who asked about examples.

API reference documentation for plugins are on pub. See https://pub.dev/documentation/device_calendar/latest/device_calendar/device_calendar-library.html. PRs are welcome for where you feel there are gaps

**Comment by GursheeshSingh** [comment]
Here is a blog - https://itnext.io/using-device-calendar-library-in-flutter-to-communicate-with-android-ios-calendar-95b2d8c77b40

**Comment by Brett09** [comment]
Just an update: I have added some examples and links into the example readme. You can check it out on `develop` branch for now.
Quick link: https://github.com/builttoroam/flutter_plugins/blob/develop/device_calendar/example/README.md

**Comment by Brett09** [comment]
Documentation has been updated and published in pub.dev [here](https://pub.dev/packages/device_calendar) - Examples are not shown correctly at the moment.

Examples are available in the repo [here](https://github.com/builttoroam/flutter_plugins/blob/master/device_calendar/example/README.md).

I'll fix to show the examples in the pub.dev site and add more examples in the future.
