### ISSUE TITLE
Android not coming back from _deviceCalendarPlugin.requestPermissions()

### ISSUE THREAD

**Issue by davidBarbieri** [builttoroam/flutter_plugins#120]
Hi, thanks for this awesome plugin!

I'm having a little permissions problem with Android.
When i open for the first time, the page that hosts the calendar, i'm prompted to allow access to the calendar, when i click accept tho, the app doesn't continue the execution, looks like the Future from the method channel is never returning anything at it just hangs there.
The permission is correctly set tho, as if i go back to the home page and click on the calendar page again, the calendar is loaded.

```
var permissionsGranted = await _deviceCalendarPlugin.hasPermissions();
      if (permissionsGranted.isSuccess && !permissionsGranted.data) {
        permissionsGranted = await _deviceCalendarPlugin.requestPermissions();

  // code dies here for Android     

   if (!permissionsGranted.isSuccess || !permissionsGranted.data) {
          return;
        }
      }
....

```
On IOS the execution is passed back to my code as expected.

Hope you have some clues about it.

Thanks!

David

**Comment by nickrandolph** [comment]
Hi David,
Can I ask you to run up the example app that's in the source code and confirm that you see similar behaviour there? If you have to modify the source code to reproduce the behaviour, please submit that as a WIP PR so that we can easily reproduce the issue.
Thanks

**Comment by davidBarbieri** [comment]
Hi Nick, thanks for the answer! 

After some troubleshooting i remembered i had written a custom handler for permissions management in MainActivity.java, which is catching all permissions requests:

```
@Override
    public void onRequestPermissionsResult(int requestCode, String[] perms, int[] grantResults) {
        if (requestCode == CODE_ASK_PERMISSION && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            try {
                shareFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
            //return true;
        }
        //return false;
    }
```

The here is where the flow gets stuck, as the first IF is false and the return value is null, this used only for the file sharing part of the app... and it was kind of a prototype.
I took a look at the kotlin code of your Plugin and i think i could structure my share plugin in the same way (as Delegate), hoping the two request permissions would not conflict.

I think this can be closed as it's an issue with my Android code.

Miss my two years in NZ and Australia, speccially the months in the Blue Mountains!

Cheers mate!

**Comment by davidBarbieri** [comment]
Refactoring done, now everything works perfectly.

Cheers

**Comment by CoreyCole** [comment]
@davidBarbieri @nickrandolph can you shed more light on this issue? I'm having the same problem because I implemented my own `onRequestPermissionsResult()` and I need it for my apps functionality. How did you refactor your code so that they don't conflict with each other? I've made sure my permission request codes don't conflict with device_calendar's (0 to 5):

```dart
fun IntArray.containsOnly(num: Int): Boolean = filter { it == num }.isNotEmpty()
override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
    print("request code = $requestCode")
    if (requestCode == MIC_PERMISSION_REQUEST_CODE || requestCode == CAMERA_PERMISSION_REQUEST_CODE) {
        val granted = grantResults.containsOnly(PackageManager.PERMISSION_GRANTED)
        currentResult?.success(granted);
        currentResult = null
    } else {
        // calendar permission lands here
    }
}
```

**Comment by CoreyCole** [comment]
I solved the issue by handling calendar permissions through my own platform channel (where I was already doing mic/camera permissions)
