### ISSUE TITLE
Cannot create a new event when passing in an `eventId`.

### ISSUE THREAD

**Issue by jeffscaturro-aka** [builttoroam/flutter_plugins#121]
What
---
When trying to create a new event (`createOrUpdateEvent`) and specifying an `eventId`, I'm receiving the following error:
```
[599] Device calendar plugin ran into an issue. Platform specific exception [404], with message :"The event with the ID 93861039 could not be found", has been thrown.
```

Environment
---
Testing on a physical iPhone X running 13.2 and an iOS Simulator (iPhone 11 Pro Max - 13.0). 

I could not reproduce this issue on Android.

Steps to Reproduce
---
Try to create a new event on iOS and specify an `eventId`.

Miscellaneous
---
I am guessing that we should not be allowed to create an event with an `eventId` and instead that's used to query for one on each platform. However, if that's the case, we need to update the documentation to avoid confusion on that.

**Comment by Rahul1703** [comment]
eventid is a read-only property when you will add into the calendar you will receive eventid.

**Comment by jeffscaturro-aka** [comment]
Sounds good - sorry for the delayed reply, lost track of this one. 

Feel free to close this out, or mark it as an enhancement for documentation purposes to make that more clear to the consumer.

**Comment by Brett09** [comment]
As @Rahul1703 said, the `eventId` field is a read-only variable so you won't be able to create an event with custom ID.

I've updated the property summary to present them as a read-only variable for now in #146 (Possibly assigning those kind of properties to only have a getter in future).

If you'd like to use a custom ID, I recommend to use the URL field (if you're not planning to use it, of course) added from v1.0.0+3.

**Comment by jeffscaturro-aka** [comment]
Thanks for the follow-up and info @Brett09, I appreciate it.
