### ISSUE TITLE
Creating an event with an `eventId` being a String of just numbers.

### ISSUE THREAD

**Issue by jeffscaturro-aka** [builttoroam/flutter_plugins#122]
What
---
It appears that when creating an event and trying to add it to the calendar with an `eventId` of just numbers (i.e. `'93861039'`) fails to actually add the event to the calendar.

Environment
---
Testing on a physical Pixel 3, running **Android** 10. Selecting a calendar from Google Calendars.

I could not reproduce this on iOS due to a different issue (#121). This might be related to that.

Steps to Reproduce
---
Take a successful `Event` that you are able to add, and change the `eventId` to `"93861039"`. Try to add the event to a calendar. You should get a successful result from the plugin, however it should never get added to your calendar.

Miscellaneous
---
I'm wondering if it's parsing to an `int` or something in plugin code, or if Google Calendars doesn't allow an `eventId` with a String of just numbers.

**Comment by Brett09** [comment]
Equivalent to #121.

As a side note, `eventId` generated from iOS is a complex string mixed with GUID. For example, I received this as an eventId when debugging: 
`eventId : "4A74FDEC-D0BC-4392-8BA0-8FCD732EA260:330AF951-9B49-4630-B112-DA38DBABBEFE"`

**Comment by jeffscaturro-aka** [comment]
Same here, thanks for the follow-up and info @Brett09, I appreciate it.
