### ISSUE TITLE
add to table_calendar package

### ISSUE THREAD

**Issue by jmsandamil** [builttoroam/flutter_plugins#124]
hello

is posible to add this events to a flutter app calendar, like table_calendar?

**Comment by nickrandolph** [comment]
yes, you can add events to the table_calendar but you need to retrieve them from the device calendar first before adding them to the calendar widget.

**Comment by jmsandamil** [comment]
sorry I am very noob, how I can do this?

**Comment by jmsandamil** [comment]
yes but I don't know how to add to the table calendar after create event, I can add your events to phone but not to table calendar example, I can't get it,


sorry for being so heavy, I appreciate the help
