### ISSUE TITLE
Allow to use our own eventId

### ISSUE THREAD

**Issue by Ionys320** [builttoroam/flutter_plugins#128]
Hello,
It would be very usefull to allow us to use our own eventId. In my case, the events come from the network, so there have an id. But if I want to add them in the calendar, I must memorize in my app the eventId returned by the plugin and associate them to the event fetched from the network, and it's not very simple.

If you can do something, it would be great !

**Comment by Brett09** [comment]
Hi,

The Event ID is an unique ID generated by each platform, which in this case cannot be manually set or changed.

**Comment by nickrandolph** [comment]
@Ionys320 check out https://github.com/builttoroam/flutter_plugins/issues/132
to use the url property for a unique ID
This issue was resolved in this PR: https://github.com/builttoroam/flutter_plugins/pull/136
and has been released
