### ISSUE TITLE
On Android there is a list of guests even though there were no attendees

### ISSUE THREAD

**Issue by finpro-svn** [builttoroam/flutter_plugins#129]
When I create an Event using the Event.fromJson method and I do not specify any attendee. When I createOrUpdateEvent the event is added to Android calendar, however in the calendar states:
"The full guest list has been hidden because the number of guests is too large."

If I do not specify any attendees there should be no guest on the guest list.

**Comment by Brett09** [comment]
Hi,

Which email account have you used to experience the issue? I cannot reproduce this issue with Office 365 and Gmail accounts.

**Comment by Brett09** [comment]
With the latest release (v3.0.0+3), haven't noticed such issue. As this ticket is outdated, I'm going to close this. Feel free to open a new ticket if you still experience the issue with the latest release.

**Comment by finpro-svn** [comment]
For me the version 3.0.0+3 fixed the problem. There are no guests any more in the Event,  when I do not specify any attendee. Thank you.
