### ISSUE TITLE
Custom url for calendar events

### ISSUE THREAD

**Issue by aloisdeniel** [builttoroam/flutter_plugins#132]
It would be great to have an `url` property at the event level to be able to identify (update for example) an event.

The property seems to be available on both platform :

* [iOS](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507265-url)
* [Android](https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns.html#CUSTOM_APP_URI)

**Comment by nickrandolph** [comment]
@aloisdeniel this was added in https://github.com/builttoroam/flutter_plugins/pull/136
and has now been published

**Comment by aloisdeniel** [comment]
Thanks a lot @nickrandolph ! 

If I may ... a great addition would be to be able to retrieve an event from its url too! :)

```dart
     final events = await systemCalendar.retrieveEvents(calendarId, RetrieveEventsParams(
eventUrls : ["custom://events/563"],
));
```

**Comment by nickrandolph** [comment]
@aloisdeniel we'll have to investigate how easily we can search for events on each platform based on the url attribute.
