### ISSUE TITLE
Add how to create a proguard file to documentation

### ISSUE THREAD

**Issue by Iiridayn** [builttoroam/flutter_plugins#133]
I am a complete newbie at Flutter and Android development in general. This is literally my first attempt at an app, and it's coursework level. Turns out, #99 applies now to newbies. Could we document how to create a proguard file, from https://flutter.dev/docs/deployment/android#step-1---configure-proguard, so we have the file to add the line to? I'm going to wrap up my classwork submission now and head home to sleep.

**Comment by MaikuB** [comment]
I would say it doesn't make sense to do so. Otherwise, it would mean every plugin should be telling users how to do it and have to update the information in case it changes. This wouldn't be sustainable for maintainers. Moreover, it's a process that belongs to the Flutter documentation (and Android documentation) as devs read through what's required when creating and submitting a release build

**Comment by Iiridayn** [comment]
I would at least suggest changing the documentation from "If you have Proguard enabled..." to dropping the caveat. Yes, developers should know everything about every system they work with, should read the documentation of every system they rely on completely before writing a line of code, etc. Even I don't know every vim feature. I've not read every line of the linux kernel. Frankly, the Firefox code overwhelmed me the last two times I tried to look at it.

Perhaps every Flutter developer who builds an Android release build (with one exception) already knows what proguard is and expects it to be enabled, even without a file in the tree. If so, you _should_ disregard my suggestion to add words (though, given we're all proguard users, deleting the caveat would still be useful). I honestly am unfamiliar enough with the whole community to know - though, given how easy it was to use the core documentation (shockingly easy, though the abstraction leaks are overwhelming without a foundation in Android development), I'd wager there is or will be a decent percentage of Flutter developers who like me have no idea what's being wrapped (and unlike me, most probably won't be worried about that, sadly).

I don't intend to do Flutter development longer term (too many layers of abstraction, though if I build another mobile app I'll reach for it first). I had thought in passing something like "create this file with this line in it, or add to existing file" wouldn't be hard to change in the documentation. Please forgive me if I was abrupt, or am again - my only intention is to share appreciation for this library by giving feedback on how it might have been an even smoother experience (and my 4 hours tracking this issue down _despite knowing_ proguard users had something special to do wasn't something I'd wish on the next idiot either, since I'd read the available docs before using the library!). Yeah, sorry. Tired. Sometimes raw emotion is good, more often not. God bless you.

**Comment by Brett09** [comment]
There is a useful guide for enabling Proguard in Android developer page (https://developer.android.com/studio/build/shrink-code).
This is added into the readme file in #140
