### ISSUE TITLE
DayOfWeekGroup error

### ISSUE THREAD

**Issue by samcromer17** [builttoroam/flutter_plugins#161]
I am trying to build the example in my existing app and the DayOfWeekGroup is erroring as undefined, its the only error I am receiving but its stopping me from building the code. Its not in the calendar_enums so I dont know if it wasnt added since its a feature that was added 2 days ago.

![Capture](https://user-images.githubusercontent.com/48026947/73488437-8da3b080-436e-11ea-98bc-a5e557394024.JPG)

**Comment by Brett09** [comment]
@samcromer17 `DayOfWeekGroup` is not available as it is not published yet. Use the existing `DayOfWeek` enum as a workaround until the new version is released.

**Comment by samcromer17** [comment]
So just replace DayOfWeekGroup with DayOfWeek? Sent from Mail for Windows 10 From: Brett LimSent: Thursday, January 30, 2020 4:28 PMTo: builttoroam/flutter_pluginsCc: samcromer17; MentionSubject: Re: [builttoroam/flutter_plugins] DayOfWeekGroup error (#161) @samcromer17 DayOfWeekGroup is not available as it is not published yet. Use the existing DayOfWeek enum as a workaround until the new version is released.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by samcromer17** [comment]
There isn’t a .None value for DayOfWeek like there is for the Group, are we supposed to use Monday? Sent from Mail for Windows 10 From: Brett LimSent: Thursday, January 30, 2020 4:28 PMTo: builttoroam/flutter_pluginsCc: samcromer17; MentionSubject: Re: [builttoroam/flutter_plugins] DayOfWeekGroup error (#161) @samcromer17 DayOfWeekGroup is not available as it is not published yet. Use the existing DayOfWeek enum as a workaround until the new version is released.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Brett09** [comment]
@samcromer17 yup `DayOfWeek` enum has values from Monday to Sunday. If you want to set 'None' for `DayOfWeek` then just don't use it.

**Comment by samcromer17** [comment]
Thanks for the help
