### ISSUE TITLE
Missing "&" at line 179 in device_calendar.dart

### ISSUE THREAD

**Issue by sageata** [builttoroam/flutter_plugins#162]
I found a small error in flutter_plugins/device_calendar/lib/src/device_calendar.dart file as is missing an '&' in the if statement.

It causes all the full day events not to be added to the Calendar.

`
    else if (event.allDay != true & ((event?.calendarId?.isEmpty ?? true) || event.start == null || event.end == null || event.start.isAfter(event.end))) {
`

![image](https://user-images.githubusercontent.com/26434396/73589170-2ad82380-44ec-11ea-8a29-3fd82eac1e34.png)

Thanks you for creating this plugin ;)

**Comment by Brett09** [comment]
@sageata thanks, it has been publised to a new hotfix `v3.0.0+3`

**Comment by sageata** [comment]
@Brett09, thank you!
