### ISSUE TITLE
 Not able to add calendar event to google pixel phones.

### ISSUE THREAD

**Issue by ssivagnanam** [builttoroam/flutter_plugins#168]
I am trying to add calendar event to google pixel phone.  But i am not able to add it and i couldn't find Default calendar (My Calendar) in calendar app also.  
Is there any thing i need to setup in my app to work with google pixel phones? 

one more issue is like, i am not able to set "Timezone" while creating event.

**Comment by Brett09** [comment]
Maybe it could be a permission issue, check out the readme file [here](https://github.com/builttoroam/flutter_plugins/tree/develop/device_calendar).
You also might want to check out the example app to see examples of the api.

Timezone is not available for this api yet, it will just use the device's timezone. (Note: creating an all day event for Android have a timezone issue right now: #164)

**Comment by ssivagnanam** [comment]
Hi,
I am able to create event in calendar of Other phones (like Samsung, Redmi, etc.,).  This issue occurs only Google Pixel phones.

I am trying to create event in Australian time zone. But in calendar, start and end time is showing in GMT timezone.  Please refer the screen shot.

![Screenshot_20200212-111657_Calendar](https://user-images.githubusercontent.com/49264085/74400223-555aa280-4e43-11ea-9bba-72b962471df2.jpg)

**Comment by Brett09** [comment]
Which device and email account are you using? I've been testing with Pixel 3a with Gmail and Outlook and haven't experienced any of event or timezone issues.

The plugin should pick up the device's timezone and use it, I'd assume you have set the device timezone as Australia, not GMT right?

**Comment by ssivagnanam** [comment]
Could you please share any example code snippet to create calendar events in android.

**Comment by Brett09** [comment]
If you were able to create a calender event through other devices, you should have the code to create a new event already. But briefly, you just need to call the method `createOrUpdateEvent(Event event)` to create a new event.

Are you able to provide which exact device and email account used? I'd like to test with it to see if I can reproduce this.

**Comment by ssivagnanam** [comment]
I am using Samsung S7 Edge.  With default calendar of Calendar app.  I want to create event in "My Calendar" Calendar.  I am getting GMT as default time zone. But i have selected my time zone as AST in DateTime under settings.

For Pixel phone issue, I am trying to create event in Pixel 2 phone.  
Note: in this device, we don't have "My Calendar". so i am using my personal mail id.

**Comment by ssivagnanam** [comment]
Hi, I have observed that 
var calendarsJson = await channel.invokeMethod('retrieveCalendars');
above line of code is returning below json string as result.  
[{"a":true,"b":"2","c":"Holidays in India"},{"a":true,"b":"3","c":"Birthdays"},{"a":false,"b":"4","c":"balajitheo@gmail.com"}]
But in Calendar model, is creating object using wrong keys

  Calendar.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    isReadOnly = json['isReadOnly'];
  }

Could you please check this at your end once? 
Please let me know if any changes are required from my end.

**Comment by Brett09** [comment]
I've tried using Pixel 2 with my personal gmail and I do get the correct json results.
Maybe have to look at the [readme](https://github.com/builttoroam/flutter_plugins/blob/master/device_calendar/README.md) if you have the correct permissions and Proguard configs set correctly.

For the timezone issue, the below code is ran to get current timezone for the device:
`val currentTimeZone: TimeZone = java.util.Calendar.getInstance().timeZone`
Maybe try running the code have a look at the result in the affected device.

**Comment by ssivagnanam** [comment]
Thanks for your support.  I am able to create events in all devices after enabling proguard settings as mentioned in readme.
But still i am not able to get current timezone in created events (still event is points to UTC timezone). This issue occurs only in samsung devices.
 Is there any settings i need to do in Calendar app to set the default timezone?

**Comment by Brett09** [comment]
I'll try it out with a Samsung phone to see what I get and get back to you. Meanwhile maybe trying out changing a timezone to something else and reverting it back to what it was?

**Comment by Brett09** [comment]
@ssivagnanam I've had a good look with Samsung Galaxy S6. Here's what I found:

- The phone correctly gets the current timezone and set it - I'm in Australia so I get/set AEST
- When I look into the event details, for my case, there's no timezone set to the event, but the time seems like set as GMT timezone just like you're having
  - But when I look at the event in montly calendar view, it displays the event correctly in AEST
- This issue only occurs when you create an event with 'My Phone' - 'My calendars' calendar - Samsung's default calendar

From this, it seems like Samsung's default calendars are little different from Android calendars, I would recommend to add an account (eg. Google) and adding events to that account instead of adding to the Samsung's default calendars.

**Comment by ssivagnanam** [comment]
Yeah.  Thanks for an Update.  Please keep me posted if any updates on this request.

**Comment by Brett09** [comment]
I'm going to close this for now, will let you know if I get a chance to add timezone support to the plugin.

**Comment by Brett09** [comment]
@ssivagnanam just an update with the Samsung phone issue, as from #182, I was able to get the current timezone for the local calendar when I use `id` instead of `displayName`. I'll apply this in the next release.
