### ISSUE TITLE
Recurring events not being created, possible bug?

### ISSUE THREAD

**Issue by JKSpenc** [builttoroam/flutter_plugins#173]
Hi, I've been trying to create a Recurring Event and it does not create it at all but returns as if it was successful. It does create non recurring events properly though.

My event looks like this:
~~~~
new Event(currentCal.id,
            start: DateTime.now(),
            title: "Sample Title",
            end: DateTime.now().add(Duration(hours: 1)),
            recurrenceRule:  RecurrenceRule(RecurrenceFrequency.Weekly,
                interval: 2,
                daysOfWeek: [DayOfWeek.Wednesday, DayOfWeek.Thursday],
                endDate: DateTime.now().add(Duration(days: 30)))
        );
~~~~

I did some digging in the kotlin code and found that a recurring event was being created with the values:
~~~~
eventTimezone=Greenwich Mean Time description=null title=Sample Title dtend=1583079854165 allDay=false dtstart=1583076254165 calendar_id=1 eventLocation=null duration=null rrule=FREQ=WEEKLY;INTERVAL=2;BYDAY=WE,TH;UNTIL=20200331T152414Z customAppUri=null
~~~~

The recurrence rule is correct but android documentation states that we should [use **duration** rather than **dtend** for recurring events. ](https://developer.android.com/reference/android/provider/CalendarContract.Events.html)

I can't verify this problem is the same in iOS as I don't have access to a Mac.

Cheers in advance.

**Comment by JKSpenc** [comment]
Sidenote: The device it is being ran on is an Android Emulator running API 21, Android 5.0 (Google APIs)

**Comment by JKSpenc** [comment]
Ignore me, the events are being created but the Google Calendar android app is not showing them. Detailed in https://support.google.com/calendar/thread/3819423?hl=en

**Comment by jackgitsource** [comment]
It is the same in iOS
