### ISSUE TITLE
Add ACCOUNT_NAME and ACCOUNT_TYPE to Calendar data

### ISSUE THREAD

**Issue by kinex** [builttoroam/flutter_plugins#179]
Calendar data is missing ACCOUNT_NAME and ACCOUNT_TYPE (referring to Android API terms). Those fields would allow displaying prettier list of available calendars to users, for example grouped by account name.

https://developer.android.com/reference/android/provider/CalendarContract.SyncColumns#ACCOUNT_NAME

**Comment by Brett09** [comment]
Do you know if there are iOS equivalent variables? We need to have the consistency between platforms.

**Comment by Brett09** [comment]
I've found iOS variables and applied them. I'll try to add this to the next release.

fyi, iOS uses `EKSource` for account information [found here](https://developer.apple.com/documentation/eventkit/eksource)

**Comment by Brett09** [comment]
v3.1.0 has been published and you'll be able to get account name and type under `Calendar` model
