### ISSUE TITLE
Incorrect value set to Events.EVENT_TIMEZONE (Android)

### ISSUE THREAD

**Issue by kinex** [builttoroam/flutter_plugins#182]
I have been investigating some timezone related issues and found this in the plugin code:
https://github.com/builttoroam/flutter_plugins/blob/develop/device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt#L390

I am quite sure `displayName` is not the correct value to put there, you should use `ID` instead (as told e.g. [here](https://stackoverflow.com/questions/11934465/eventtimezone-value)).

So why does it seem to work then without issues? I think this is because the value (`DateTime.millisecondsSinceEpoch`) passed from Dart is UTC time. Setting invalid value to `EVENT_TIMEZONE` is probably ignored and actual timezone is reverted to UTC. 

So I think it is also a bug even trying to put the current device timezone to EVENT_TIMEZONE, because the `Event.start` is UTC. 

Fix options:
1. Save in `EVENT_TIMEZONE` the UTC timezone.
2. Convert Event start/end to local time and save in `EVENT_TIMEZONE` the device timezone.
3. Remove setting `EVENT_TIMEZONE` at all? Maybe the default is UTC? Should be tested.

Or have I misunderstood something?

**Comment by Brett09** [comment]
I haven't seen any issue with using `displayName` except it uses wrong (or null) timezone when you use your local calendar in Samsung phones. Just tried out with using `id` and it seems to be working.
Thanks for the point and I'll put this in so it's available in the next release.

**Comment by Brett09** [comment]
All `TimeZone` variables are now using `id` in v3.1.0, closing this ticket.
