### ISSUE TITLE
Calendar functionality not working in release mode

### ISSUE THREAD

**Issue by eliseyOzerov** [builttoroam/flutter_plugins#184]
Hi,

I have an unusual problem going on, and the title pretty much describes it.

Basically, my task is to enable adding and removing events from the device calendar. This works properly when I'm in the debug or run --release modes, but not after I build the apk and launch it independently from VSCode.

I was wondering if anybody has encountered this issue and knows something that might help.

Please do tell if you want to see the code.

EDIT:

I've progressed a bit on the issue and found out that I can't add events because when retrieveCalendars is called, it returns the calendars, but they contain no data - id, name and isReadOnly are all 'null' in every calendar and I don't know where to go from here.

**Comment by Brett09** [comment]
Possible duplicate, please refer to this issue: https://github.com/builttoroam/flutter_plugins/issues/99

The readme has some information about Proguard already but I'll probably leave an extra note so it's easier to catch for this kind of issue.
