### ISSUE TITLE
Ios Simulator createOrUpdate event not working.

### ISSUE THREAD

**Issue by hardypatel30** [builttoroam/flutter_plugins#185]
While adding event to the calendar in simulator it is giving me below error.

PlatformException(405, Calendar with ID E0E5295C-DCDA-47BF-9161-4C7F08F94A68 is read-only, null)

**Comment by Brett09** [comment]
As the error says, the calendar you're trying to use is read-only and you're not allowed to add/edit or delete the calendar.
