### ISSUE TITLE
Missing android createCalendar

### ISSUE THREAD

**Issue by jurjukn** [builttoroam/flutter_plugins#196]
Missmatch between flutter and android versions. Flutter has createCalendar method, while android version does not have it. Therefor it throws exception when creating a calendor

**Comment by Brett09** [comment]
Create calendar is not supported in the current version. Not sure where you got the method from, but a pre-release has been published [here](https://pub.dev/packages/device_calendar/versions/3.1.0-dev.11079) (v3.1.0-dev.11079) and it supports creating a calendar.

You can have a look at the pre-release for now, a stable version will be released later.

**Comment by Brett09** [comment]
v3.1.0 has been published, you should be able to create calendars in both platforms. Feel free to open a new issue ticket if you face any issues
