### ISSUE TITLE
daysOfWeek form json don't return the right dates

### ISSUE THREAD

**Issue by kabwizi** [builttoroam/flutter_plugins#210]
when trying to add an event to the calendar with json, Example: List <int> [1,2,5] (for daysOfWeek); with the recurrenceRule.toJson () method, it is not the good days that are saved in the calendar. but when we do it without the ToJson () method; it works perfectly.

**Comment by Brett09** [comment]
Can you elaborate more? I don't get what you're trying to explain here.

Also, you don't need to call `toJson` or `fromJson` in the code as `retrieveEvents` and `createOrUpdateEvent` methods in the plugin automatically encode/decode the `Event` object.

**Comment by kabwizi** [comment]
//like so
createEvent(_calendars, _deviceCalendarPlugin) {
  Map<String, dynamic> eventMap = {
    "eventId": "125",
    "calendarId": _calendars.id,
    "title": "event title",
    "start": DateTime.now().millisecondsSinceEpoch,
    "end": DateTime.now().add(Duration(days: 2)).millisecondsSinceEpoch,
    "allDay": false,
    "reminders": [Reminder(minutes: 30).toJson()],
    "recurrenceRule": RecurrenceRule(RecurrenceFrequency.Weekly,
        interval: 1,
        endDate: DateTime.now().add(Duration(days: 20)),
        daysOfWeek: [
          DayOfWeek.Friday,
          `DayOfWeek.Saturday,`
          DayOfWeek.Wednesday
        ]).toJson(),
  };
  _deviceCalendarPlugin.createOrUpdateEvent(Event.fromJson(eventMap));
`}`

**Comment by kabwizi** [comment]
if you try with this code, the date that will be saved in the calendar will not have the correct dates either DayOfWeek.Friday,
DayOfWeek.Saturday,
DayOfWeek.Wednesday

**Comment by kabwizi** [comment]
//like so:
createEvent(
    Calendar _calendars, DeviceCalendarPlugin _deviceCalendarPlugin) async {
  Map<String, dynamic> eventMap = {
    "eventId": "etgsh",
    "calendarId": _calendars.id,
    "title": "title event",
    "start": DateTime.now().add(Duration(hours: 1)).millisecondsSinceEpoch,
    "end": DateTime.now().add(Duration(hours: 3)).millisecondsSinceEpoch,
    "allDay": false,
    "reminders": [Reminder(minutes: 30).toJson()],
    "recurrenceRule": RecurrenceRule(RecurrenceFrequency.Weekly,
        interval: 1,
        endDate: DateTime.now().add(Duration(days: 20)),
        daysOfWeek: [
          DayOfWeek.Friday,
          DayOfWeek.Saturday,
          DayOfWeek.Wednesday
        ]).toJson(),
  };
  await _deviceCalendarPlugin
      .createOrUpdateEvent(Event.fromJson(eventMap))
      .then((onValue) {
    print("==${onValue.isSuccess}==");
  });
}

**Comment by kabwizi** [comment]
if you try with this code, the date that will be saved in the calendar will not have the correct dates either : DayOfWeek.Friday,
DayOfWeek.Saturday,
DayOfWeek.Wednesday

**Comment by Brett09** [comment]
Is there a reason you're creating an event object as a Map? There is `Event` object in the plugin and you can use that object to assign event properties and call `createOrUpdateEvent()` method.
Also, you shouldn't assign event ids unless you know that id is correct and you're editing the event.

I've tested with the example app in the plugin with the same recurrence rule and I can see it is getting the correct dates.

**Comment by kabwizi** [comment]
Is there a reason you're creating an event object as a Map? 
yes. because with the  Event object 
we do not have the possibility to set manualy reminders.

**Comment by kabwizi** [comment]
Is there a reason you're creating an event object as a Map?
yes. because with the Event object
we do not have the possibility to set manualy reminders.
is there a way to do that with the event object?

**Comment by kabwizi** [comment]
thanks in advance for your time

**Comment by Brett09** [comment]
Yes there is. See [here](https://github.com/builttoroam/flutter_plugins/blob/master/device_calendar/lib/src/models/event.dart) - there is a property called `reminders` with type of `List<Reminder>`.

**Comment by kabwizi** [comment]
thank you again for having found the time to answer me. I had time to see your code, but I don't know, maybe it is me who doesn't understand, but your constructor Event (this.calendarId,
      {this.eventId,
      this.title,
      this.start,
      this.end,
      this.description,
      this.attendees,
      this.recurrenceRule,
      this.allDay = false});
 does not accept List <Reminder> reminders.
there is only the constructor Event.fromJson (Map <String, dynamic> json) which does it

**Comment by kabwizi** [comment]
thank you again for having found the time to answer me. I had time to see your code, but I don't know, maybe it is me who doesn't understand, but your constructor `Event (this.calendarId,
{this.eventId,
this.title,
this.start,
this.end,
this.description,
this.attendees,
this.recurrenceRule,
this.allDay = false});`
does not accept List reminders.
there is only the constructor `Event.fromJson (Map <String, dynamic> json)` which does it like so `    if (json['reminders'] != null) {
      reminders = json['reminders'].map<Reminder>((decodedReminder) {
        return Reminder.fromJson(decodedReminder);
      }).toList();
    }`

**Comment by kabwizi** [comment]
thank you again for having found the time to answer me. I had time to see your code, but I don't know, maybe it is me who doesn't understand, but your constructor Event (this.calendarId, {this.eventId, this.title, this.start, this.end, this.description, this.attendees, this.recurrenceRule, this.allDay = false});
does not accept `List<reminders>.`
there is only the constructor Event.fromJson (Map <String, dynamic> json) which does it like so if (json['reminders'] != null) { reminders = json['reminders'].map<Reminder>((decodedReminder) { return Reminder.fromJson(decodedReminder); }).toList(); }

**Comment by kabwizi** [comment]
thank you again for having found the time to answer me. I had time to see your code, but I don't know, maybe it is me who doesn't understand, but your constructor `Event (this.calendarId, {this.eventId, this.title, this.start, this.end, this.description, this.attendees, this.recurrenceRule, this.allDay = false});`
does not accept `List<Reminders>.`
there is only the constructor `Event.fromJson (Map <String, dynamic> json)` which does it like so ` if (json['reminders'] != null) { reminders = json['reminders'].map<Reminder>((decodedReminder) { return Reminder.fromJson(decodedReminder); }).toList(); }`

**Comment by Brett09** [comment]
Ah good point, no idea why `reminder` is not part of the constructor, I'll make sure to add it in the next release. As a workaround, you can directly assign to the property. For example:
```dart
var reminders = List<Reminder>();
reminders.add(Reminder(minutes: 30));

var event = Event("1", title: "Test Event");
event.reminders = reminders;
```

**Comment by kabwizi** [comment]
thank you very much Brett09 for still finding the time to answer me, I can't wait to see your next publication for this plugin, otherwise, congratulations for the great work you have done with this plugin, your code is magnificent and you have it made easy to understand for everyone (I"m French speaking, so I know what I'm saying). I wish you a good continuation for the future. And again congratulations for this great work.
