### ISSUE TITLE
Can't compile device_calendar on iOS

### ISSUE THREAD

**Issue by shinyford** [builttoroam/flutter_plugins#60]
Hi - device_calendar is great on Android, but fails to compile on iOS with the following error:

`/Users/nicford/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-0.0.6/ios/Classes/DeviceCalendarPlugin.m:2:9: 'device_calendar/device_calendar-Swift.h' file not found`

I've trawled Google and found many references to similar problems; but none of which have solved the problem for me. Is this something you've come across before? And if so, do you have a fix?

Many thanks

Nic Ford

**Comment by MaikuB** [comment]
I assume your app got created with an Objective-C iOS head project? If so, you may need to modify the podfile for your app as per mravn-google's post at https://github.com/flutter/flutter/issues/16049

If this works for you (seems to work for me) then let us know and we'll update the README

**Comment by MaikuB** [comment]
Closing due to a lack of response. If this is still an issue then feel free to reopen this

**Comment by thanhhuan1990** [comment]
I got this issue in ver.0.1.1:

/Users/apple/Development/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-0.1.1/ios/Classes/DeviceCalendarPlugin.m:2:9: 'device_calendar/device_calendar-Swift.h' file not found

Thanks

**Comment by thanhhuan1990** [comment]
Its worked now, this helped me.
target 'Runner' do
  use_frameworks! # <--- add this
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0' # <--- add this
    end
  end
end

**Comment by l-k22** [comment]
I can't use "use_frameworks!" because it conflicts with the onesignal notification package. Is there away to exclude this function on certain packages?
