### ISSUE TITLE
Recurring Event

### ISSUE THREAD

**Issue by Solido** [builttoroam/flutter_plugins#62]
Hi

I've started working with your lib and it's working well +1
I'd like to add more advanced feature like recurring events or others specific events.

Is there so methods calls that will be available in coming release or should I manage it all from Flutter ?

Thanks.

**Comment by nickrandolph** [comment]
@Solido building support for recurring events is definitely on the backlog. However, at this stage we haven't got a timeframe for implementing it. 
Definitely happy to take contributions if you want to submit a PR

**Comment by nickrandolph** [comment]
The Dart API that's exposed to developers should reflect as much consistency across all platforms as possible. 

If there are features that some platforms expose but not all, the plugin should expose a property indicating whether a feature is supported. The feature should be exposed in a way that makes it possible to add other platform support later (eg no exposing Android or iOS specific class/package names)

It'd be worth looking at what API plugins for other ecosystems expose (eg Xamarin/Xamarin.Form or ReactNative).

**Comment by Solido** [comment]
My point is how to get this available to the users by ANY means ;)
Few chance that the lib get adopted if it can't let you access to advanced methods but how to get it implemented is not an easy task !

**Comment by Solido** [comment]
Not sure if it helps but you could also have a look at RN
https://github.com/wmcmahan/react-native-calendar-events

**Comment by nickrandolph** [comment]
@Solido I'm not sure what your comment about adoption means. If developers want more advanced functionality, they are more than welcome to fork this repo and build out their own features. 
Thanks for the links to RN - we can use some of that as the basis for how we build out recurring events but it'd be great to get someone from the community to assist.

**Comment by Solido** [comment]
Let me know how I can help

**Comment by gthirumurugan** [comment]
@MaikuB 

I am using your library for one of my Application - it is working great and thank you.

@Solido @MaikuB 

BTW, i also need the reminder functionality and wondering if any work has gone into it. If not, I am planning to start working on it but thought of checking in first to avoid duplicate effort.

Thank you again and please do let me know your comments!

**Comment by MaikuB** [comment]
@gthirumurugan we haven't done any work on this so you are welcome to submit a PR as mentioned above

**Comment by gthirumurugan** [comment]
@MaikuB 

Thank you for responding - I'll submit a PR once I am finished with the enhancements. For now, I am planning to go by the RN design as @Solido has pointed out.

**Comment by nickrandolph** [comment]
@Solido for now there is a basic implementation of recurring appointments. We'll open up issues for extending the implementation shortly
