### ISSUE TITLE
Create Event with specific ID

### ISSUE THREAD

**Issue by Solido** [builttoroam/flutter_plugins#63]
Current implementation assume that a provided ID is for update but
I'd like to manage events by forging it. Is it possible ?
These would help a lot manage complex operations.
Thank you.

**Comment by MaikuB** [comment]
It's not possible as the ID is generated by native APIs upon event creation, particularly on iOS.

**Comment by nickrandolph** [comment]
@Solido can you elaborate on your scenario please?

**Comment by Solido** [comment]
2 cases 

First I was thinking than in IOS recurring event are managed like this that's why you can ask for the first even of the same id. Thus I can easily manage them. Can you confirm or infirm this ?

Second I can forge id like PROJECTID-ANYDIGIT then it's easy to bind event to other entities in my project.

**Comment by Solido** [comment]
Guess this won't be possible so I close.
Thanks guys !
