### ISSUE TITLE
Kotlin Gradle plugin version 1.2.51 and higher

### ISSUE THREAD

**Issue by mabinici** [builttoroam/flutter_plugins#68]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'device_calendar' is using version
1.1.51.

**Comment by mabinici** [comment]
The package is still 0.0.6. Is it going to be updated with this issue resolved?

**Comment by MaikuB** [comment]
PR #69 by @huzhiren should fix this issue. Closing this issue. Feel free to re-open if this is still an issue
