### ISSUE TITLE
New Pixel without device calendar 

### ISSUE THREAD

**Issue by kadaha** [builttoroam/flutter_plugins#74]
Hi, 
The issue is more android related: 
The plugin works very well on a device that has a built in calendar and usually that calendar is sync with email calendars of the user, but i can't make it work with a google pixel 2 because my guess is there is no built in calendar, i was wondering how would it be possible to make it work with a phone that has only google calendar and if it was possible or a way around.

Thanks a lot

**Comment by MichaelPriebe** [comment]
I was wondering why this plugin was doing absolutely nothing. Its because my emulator is a pixel with Google Calendar.

**Comment by MaikuB** [comment]
I use this on a Google Pixel 2 XL and the built in calendar is Google calendar. If you're running this on an emulator then you'll need to ensure you have run the calendar app and signed in beforehand

**Comment by MaikuB** [comment]
Are you able to provide steps to reproduce the scenario?

**Comment by MaikuB** [comment]
Closing this due to lack of further response. Feel free to re-open if you're able to provide more details
