### ISSUE TITLE
Adding attendees when creating an event

### ISSUE THREAD

**Issue by GlennHendriksen** [builttoroam/flutter_plugins#75]
Hello there,

I have a problem with attendees. I'm creating calendar events for a flutter app I'm building. The user can select a person that he wants to schedule a meeting with, the app creates an event in the users calendar. Now I'm at the point that I want to add the selected person as an attendee so that the calendar event will be send to this person, and the selected person can accept/deny the invitation. 

My problem is the following: I can't add attendees based on their e-mail address. The Attendee class only has a name property and (as far as I have tested) doesn't add anything to the actual event when I check the android calendar. Are there any plans to support this? Or am I doing something wrong?
This functionality sort of "makes or breaks" the plugin for me.

**Comment by MaikuB** [comment]
We could potentially look at this in the future. Feel free to submit a PR

**Comment by MaikuB** [comment]
Just a follow-up on this, it's not possible to add attendees, at least not on iOS. See [here](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507140-attendees) for documentation about this

**Comment by thanhhuan1990** [comment]
> Just a follow-up on this, it's not possible to add attendees, at least not on iOS. See [here](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507140-attendees) for documentation about this

Actually, now I can create an event with attendees by two step:

1. Create event by code from this package.
2. Insert or edit attendees for iOS and android by my native code. 
Android: ContentResolver + CalendarContract.
iOS: EKParticipant + ekEvent!.setValue(attendees, forKey: "attendees")

Thanks for your response.

**Comment by MaikuB** [comment]
Thanks for the info, we know it can be done in Android and did recently come across that way you mentioned for iOS

**Comment by MaikuB** [comment]
@thanhhuan1990 what versions of iOS did you run the code on? there have been accounts of this approach not working in the past, which is a concern https://stackoverflow.com/questions/30627694/modifying-ekparticipants-attendees-in-eventkit-like-sunrise

**Comment by thanhhuan1990** [comment]
I'm not sure for all iOS version, but I released my application on Testflight for my team member (near 30 members), they use iPhone from 5s ~ X, and no problem happen with them until now.
If you found any issue about this, please let me know, thanks.

**Comment by MaikuB** [comment]
This should be in the latest release
