### ISSUE TITLE
Request Permission problem

### ISSUE THREAD

**Issue by trompetin17** [builttoroam/flutter_plugins#79]
Hi, when you have more that one plugin that uses onRequestPermissionsResult the other plugins was unable to receive this result because you are turning true here:

https://github.com/builttoroam/flutter_plugins/blob/addcd289a1a909892ab6408e3866dc4528020dcd/device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt#L93

Reading the source code you must return true only if you handle it if you don't handle you must return false.

**Comment by MaikuB** [comment]
Thanks for the info, will take a look at addressing this

**Comment by gerryhigh** [comment]
This is still broken. It is blindly returning true for a permission and return true at line 84 even it the permission (e.g. FINE LOCATION) is not what is being requested. Minimally check the permission type as well (not just the request code). This is a show stopper and was breaking the location plugin.

**Comment by MaikuB** [comment]
@gerryhigh any chance you could submit a PR as it seems like you have a fork for this already?

**Comment by uzairamer** [comment]
Someone needs to fix this ASAP, it has affected the location plugin.

**Comment by nickrandolph** [comment]
@uzairamer feel free to contribute a fix as this is an open source plugin....

**Comment by gerryhigh** [comment]
> @gerryhigh any chance you could submit a PR as it seems like you have a fork for this already?

I just submitted a PR. My fix was to return false to the check prior to the one mentioned in this fix for issue #79.

https://docs.flutter.io/javadoc/io/flutter/plugin/common/PluginRegistry.RequestPermissionsResultListener.html

My fork is here: https://github.com/gerryhigh/flutter_plugins

**Comment by pedromassango** [comment]
Thanks for it. We need to get it solved. Anything that I can do to help?

**Comment by MaikuB** [comment]
@pedromassango if update your dependencies to point to @gerryhigh's fork then you should be able to test to see if it solves the issue for you

**Comment by MaikuB** [comment]
Have merged @gerryhigh's PR in and that's in the 0.1.2 release
