### ISSUE TITLE
SWIFT_VERSION attribute set

### ISSUE THREAD

**Issue by AdrianJCo** [builttoroam/flutter_plugins#86]
`device_calendar` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by MaikuB** [comment]
You'll likely need to do what's mentioned [here](https://github.com/builttoroam/flutter_plugins/issues/61#issuecomment-407293239) in your app. Can you let us know if that works? Hoping to get more confirmation from others that it also works for them to add this step to the readme

**Comment by AdrianJCo** [comment]
Hi Michael,

Sorry this did not work, I even deleted my existing project and started a new project but still seeing the same error.

I am using Xcode 10.1.

Best regards,
Adrian

**Comment by MaikuB** [comment]
are you able to provide a sample to reproduce the problem?

**Comment by duzenko** [comment]
I just encountered this on a new project. This is a blocking issue for me.

[test_calendar_plugin.zip](https://github.com/builttoroam/flutter_plugins/files/3186920/test_calendar_plugin.zip)

F5 in VSCode does nothing. Terminal -> flutter run outputs the following

```

Antons-Mac:test_calendar_plugin a$ flutter run
Launching lib/main.dart on iPhone 6 Plus in debug mode...
Running pod install...                                              0.6s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `device_calendar` from `.symlinks/plugins/device_calendar/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A device_calendar

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing device_calendar (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `device_calendar` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please
    contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute:
    `children`. This can be the result of a merge and  the unknown UUID is being discarded.

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this
    target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 6 Plus.
```

**Comment by MaikuB** [comment]
See https://github.com/flutter/flutter/issues/16049#issuecomment-477976754. You may need to look at downgrading Cocoapods to 1.5.0

**Comment by MaikuB** [comment]
Also an alternative solution that may you need to consider recreating your app but make it so that the iOS side is created as a Swift iOS project

**Comment by duzenko** [comment]
A different error

```
Antons-Mac:test_calendar_plugin a$ flutter run
Launching lib/main.dart on iPhone 6 Plus in debug mode...
Running Xcode build...                                                  
                                                   
Xcode build done.                                            3.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET device_calendar OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "device_calendar-umbrella.h"
            ^
    /Users/a/Documents/test_calendar_plugin/ios/Pods/Headers/Public/device_calendar/device_calendar-umbrella.h:13:9: note: in file included from
    /Users/a/Documents/test_calendar_plugin/ios/Pods/Headers/Public/device_calendar/device_calendar-umbrella.h:13:
    #import "DeviceCalendarPlugin.h"
            ^
    /Users/a/Documents/test_calendar_plugin/ios/Pods/Headers/Public/device_calendar/DeviceCalendarPlugin.h:1:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'device_calendar'

Could not build the application for the simulator.
Error launching application on iPhone 6 Plus.
```

**Comment by MaikuB** [comment]
@duzenko not sure what you actually tried but from taking another look at the project you've zipped, i've noticed that a couple of things

- no changes were made to the Podfile to address the swift version issue (see the link provided in the second post in this thread)
-  there are files missing in your project that prevent the app from being able to run even if the dependency on the calendar plugin was removed

```
   === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The file “Debug.xcconfig” couldn’t be opened because there is no such file. (/Users/michaelbui/Projects/test_calendar_plugin/ios/Flutter/Debug.xcconfig)
```

**Comment by duzenko** [comment]
Right, the folder test_calendar_plugin/ios/Flutter is about 100MB in size. Github won't allow attaching files that big.
How do I provide full repro cases when it comes to flutter projects?

**Comment by MaikuB** [comment]
You could create a repository on Github and post the link. Based on the size, it sounds like you were trying to zip the entire folder that would've included build artifacts etc generated on your machine. The `flutter clean` command could clean some of that up though uploading to repo with the .gitignore file included in your project would also ensure they're not uploaded to your repository

**Comment by nickrandolph** [comment]
Alternatively if you fork this repository you can just add your example and commit the code. Then submit a PR for us to review (we clearly won't merge the PR but it provides a good mechanism for us to see what's going on with your project).

**Comment by MaikuB** [comment]
@duzenko thanks for letting us know. A note was added in the readme in a recent release

**Comment by MaikuB** [comment]
Closing this as we have left a note in the README about consuming Swift plugins for other devs to refer to
