### ISSUE TITLE
Build error with the plgin

### ISSUE THREAD

**Issue by pneves001** [builttoroam/flutter_plugins#90]
/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-0.1.2/ios/Classes/D
    eviceCalendarPlugin.m:2:9: fatal error: 'device_calendar/device_calendar-Swift.h' file not found
    #import <device_calendar/device_calendar-Swift.h>

**Comment by pneves001** [comment]
I didn't even add any code yet. That was me just including the plugin into the project.

**Comment by MaikuB** [comment]
There's a general issue with Flutter consuming plugins developed in Swift within an Objective-C iOS project, which I assume is the scenario here as well. A link has been added to the readme with a link to the issue being tracked by the Flutter team. You may need to consider converting the iOS side of your project into Swift

**Comment by pneves001** [comment]
Well, I definitely have Objective C Plugins that are working in my project but the work I do is primarily in dart.

**Comment by MaikuB** [comment]
From what I recall, Objective-C plugins should work fine within a Swift project. It's more of an issue when it's the other way around. The plugins and your project don't necessarily need to be the same language

**Comment by adamwoodster** [comment]
Just for anyone checking this in the future (like me), I fixed this issue by making sure 'use_frameworks!' was in the Podfile.
