### ISSUE TITLE
EKCADErrorDomain 1014

### ISSUE THREAD

**Issue by duzenko** [builttoroam/flutter_plugins#94]
Getting this exception every time on iPhone 4S with this code
`      final existingEventsRes = await deviceCalendar.retrieveEvents(calendar.id, filter);`
deviceCalendar is regular (non-readonly)

`Error getting shared calendar invitations for entity types 3 from daemon: Error Domain=EKCADErrorDomain Code=1014 "(null)"`

Quick search in the internet hints a bug in iOS with a workaround described [here](
https://forums.developer.apple.com/thread/93537)

**Comment by nickrandolph** [comment]
Thanks @duzenko for reporting this. Would you be able to create a PR with the change proposed in the link you mentioned?

**Comment by duzenko** [comment]
> Thanks @duzenko for reporting this. Would you be able to create a PR with the change proposed in the link you mentioned?

I'm new to dart and flutter. PR'ing plugins is something I yet need to learn.
Moreover, this code runs just fine on a 6S so it might be an iOS9-specific issue.
I'm thinking something like (SwiftDeviceCalendarPlugin.swift/retrieveEvents)
if iOS10up
 let ekCalendar = self.eventStore.calendar(withIdentifier: calendarId)
else
 let ekCalendar = self.eventStore.calendars.firstwhere(Id == calendarId)
Does it make sense?
Where do I read about debugging/patching plugins for flutter?

**Comment by MaikuB** [comment]
Plugins make use of platform channels so I'd suggest having a read about them [here](https://flutter.dev/docs/development/platform-integration/platform-channels). You would need open the Android/iOS side of the example apps (not the plugin( in the appropriate IDE to debug the Android/iOS code for the plugin

**Comment by duzenko** [comment]
Thanks
I tried building the example app but first it gave architecture error (ARM64 vs standard) and then this
![image](https://user-images.githubusercontent.com/1481807/58888588-4c300800-86f0-11e9-8048-9d0b8f064e6d.png)

**Comment by duzenko** [comment]
Uh-oh
Looks like a bad type cast
https://stackoverflow.com/a/45094091/505984

**Comment by nickrandolph** [comment]
Closing this issue as #98 addresses this issue
