### ISSUE TITLE
Flutter build api --release issue

### ISSUE THREAD

**Issue by thanhhuan1990** [builttoroam/flutter_plugins#99]
I have been gotten issue with retrieveCalendars when build release.

If I build project by code, device_calendar work well. But if I build release apk and then install by generated apk. this method cannot retrieveCalendars on device.

Please help me about this.

Thanks

**Comment by MaikuB** [comment]
We suspect this is related to the use of Proguard and we'll investigate

**Comment by thanhhuan1990** [comment]
Thank for your response. I found problem myself but forgot update issue, it's really problem when release with Proguard, sorry for wasting your time.

**Comment by nickrandolph** [comment]
@thanhhuan1990 can you elaborate more on what the issue is/way - if would help others if we can document what the issue was

**Comment by britannio** [comment]
I had the same issue due to Proguard. I fixed it by adding the following line to my Proguard file.
`-keep class com.builttoroam.devicecalendar.**  { *; }`

**Comment by britannio** [comment]
Might be worth adding it to the readme.

**Comment by MaikuB** [comment]
Thanks @britannio, we planned to do so

**Comment by Iiridayn** [comment]
As an aside, turns out everyone is a proguard user now... This fixed my issue, even though I'm using a standard autogen flutter project with the latest release, etc. Finding it was a lucky stroke. Can how to create a proper proguard file be documented? I added the line from this issue to the file documented here https://flutter.dev/docs/deployment/android#step-1---configure-proguard .

**Comment by eliseyOzerov** [comment]
This solution worked for me for the Android build, what about the iOS? Because this bug is happening on iOS as well.

**Comment by chuckinSpace** [comment]
Where is this line supposed to go exactly?

**Comment by britannio** [comment]
> Where is this line supposed to go exactly? I know it says on the proguard file but, according to the docs it says it should be there in the project auto-generated, but in my case is not, do I suppose to create it?

`android/app/proguard-rules.pro`
Mine looks like this:
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

# You might not be using firebase
# -keep class com.google.firebase.** { *; }
-keep class com.builttoroam.devicecalendar.** { *; }
```

then in `android/app/build.gradle` add the following line to buildTypes { release  {}}
`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`

I also use `minifyEnabled true` and `shrinkResources true` in the same place.

Finally under `android/gradle.properties` I have `android.enableR8=true`, R8 still respects your proguard rules.

**Comment by Ananthan1996** [comment]
Now I can retrieve calendars in release mode by adding proguard. But for release mode deletion of event is not working.Can anyone  help me in this case.I have an important feature to release.

**Comment by technoAri** [comment]
@britannio android/app/proguard-rules.pro - this would be inside the flutter app's android/app or inside the plugin's?

**Comment by britannio** [comment]
> @britannio android/app/proguard-rules.pro - this would be inside the flutter app's android/app or inside the plugin's?

Inside your Flutter app.

**Comment by jurgenramirez** [comment]
I did not have the pro guard files before and I am creating the apk as follows
flutter build apk --release
I have added the solution that they mention but it does not work, it seems that when I generate the apk it does not take the proguard

in the gradle.properties located in android/gradle.properties add this line

android.enableR8=true

in android/app/build.gradle file add
buildTypes {
       release {
           minifyEnabled true
           shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
       }
   }

and add the file
android/app/proguard-rules.pro

#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# You might not be using firebase
-keep class com.google.firebase.** { *; }
-keep class com.builttoroam.devicecalendar.** { *; }

**Comment by jurgenramirez** [comment]
I did not have the pro guard files before and I am creating the apk as follows
flutter build apk --release
I have added the solution that they mention but it does not work, it seems that when I generate the apk it does not take the proguard

in the gradle.properties located in android/gradle.properties add this line

android.enableR8=true

in android/app/build.gradle file add
buildTypes {
       release {
           minifyEnabled true
           shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
       }
   }

and add the file
android/app/proguard-rules.pro

#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# You might not be using firebase
-keep class com.google.firebase.** { *; }
-keep class com.builttoroam.devicecalendar.** { *; }

**Comment by fraboniface** [comment]
As someone who just spent a full day on this thinking the problem came from somewhere else, you can follow the steps from @jurgenramirez but do use the proguard file of @britannio, with the endings in .** { *; }.

**Comment by rajatency** [comment]
> > Where is this line supposed to go exactly? I know it says on the proguard file but, according to the docs it says it should be there in the project auto-generated, but in my case is not, do I suppose to create it?
> 
> `android/app/proguard-rules.pro` Mine looks like this:
> 
> ```
> #Flutter Wrapper
> -keep class io.flutter.app.** { *; }
> -keep class io.flutter.plugin.**  { *; }
> -keep class io.flutter.util.**  { *; }
> -keep class io.flutter.view.**  { *; }
> -keep class io.flutter.**  { *; }
> -keep class io.flutter.plugins.**  { *; }
> 
> # You might not be using firebase
> # -keep class com.google.firebase.** { *; }
> -keep class com.builttoroam.devicecalendar.** { *; }
> ```
> 
> then in `android/app/build.gradle` add the following line to buildTypes { release {}} `proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`
> 
> I also use `minifyEnabled true` and `shrinkResources true` in the same place.
> 
> Finally under `android/gradle.properties` I have `android.enableR8=true`, R8 still respects your proguard rules.

Works!

**Comment by div-mobioxy** [comment]
> I had a similar issue due to Proguard. I fixed it by adding the following line to my Proguard file. `-keep class com.builttoroam.devicecalendar.** { *; }`

Thanks, bro. It works for me
